#!/usr/bin/env bash
# Mobile-ReverseSkill — provider sync. Idempotent.
#
# Canonical sources: skills/*/ (SKILL.md) · commands/*.md · AGENTS.md.
# The generated provider dirs are COMMITTED so a plain `git clone` works in
# every agent with zero setup:
#
#   .agents/skills/        skills — Cursor, Copilot/VS Code, Amp, Crush,
#                          Windsurf, opencode, Gemini CLI, ZCode
#   .claude/skills/        skills — Claude Code (reads only .claude/)
#   .codex/skills/         skills — Codex CLI (project-level)
#   .claude/commands/      slash commands — Claude Code
#   .opencode/commands/    slash commands — opencode
#   .agents/commands/      slash commands — ZCode (+ tools following .agents)
#   .cursor/commands/      slash commands — Cursor
#   .codex/prompts/        slash commands — Codex CLI (same frontmatter:
#                          description + argument-hint; $ARGUMENTS is native)
#   .github/prompts/       prompt files — GitHub Copilot / VS Code (*.prompt.md)
#   .windsurf/workflows/   workflows — Windsurf
#   .gemini/commands/      commands — Gemini CLI (TOML, $ARGUMENTS -> {{args}})
#   CLAUDE.md · GEMINI.md  thin @AGENTS.md import wrappers (Claude Code and
#                          Gemini don't read AGENTS.md natively)
#
#   Amp / Crush ship no custom-command files — skills cover them.
#
#   ./sync-providers.sh             regenerate the in-repo provider dirs
#   ./sync-providers.sh --check     report drift only (CI-friendly; exit 1 on drift)
#   ./sync-providers.sh --user      install skills + commands into user-global dirs
set -uo pipefail

MODE="sync"
while [ $# -gt 0 ]; do
  case "$1" in
    --check) MODE="check"; shift;;
    --user)  MODE="user";  shift;;
    -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0;;
    *) echo "unknown arg: $1" >&2; exit 2;;
  esac
done

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

ok(){   printf '  \033[32m✓\033[0m %-26s %s\n' "$1" "${2:-}"; }
miss(){ printf '  \033[31m✗\033[0m %-26s %s\n' "$1" "${2:-}"; }
note(){ printf '\033[36m[*]\033[0m %s\n' "$*"; }

WRAPPER_COMMENT='<!-- Generated by scripts/sync-providers.sh — do not edit. This tool does not read AGENTS.md natively; this wrapper imports the canonical agent guide. -->'

# frontmatter field $1 from markdown file $2 (first `---` block only)
fm_field(){
  awk -v k="$1" '
    /^---$/ { n++; next }
    n==1 && index($0, k":") == 1 { sub("^"k":[ ]*", ""); sub(/[ \t]+$/, ""); print; exit }
  ' "$2"
}

# markdown body after the closing `---` of the frontmatter
body_after_frontmatter(){
  awk '/^---$/{n++; next} n>=2 {print}' "$1" | sed -e '/./,$!d'
}

# $1 = output path, $2 = description, $3 = prompt body.
# $ARGUMENTS -> {{args}}; bodies without a $ARGUMENTS placeholder get an
# appended "Arguments: {{args}}" line so typed args still reach the prompt.
write_toml(){
  local body
  body="$(printf '%s' "$3" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')"
  if printf '%s' "$body" | grep -q '\$ARGUMENTS'; then
    body="$(printf '%s' "$body" | sed -e 's/\$ARGUMENTS/{{args}}/g')"
  else
    body="$body
Arguments: {{args}}"
  fi
  {
    printf '# Generated by scripts/sync-providers.sh — edit commands/<name>.md instead.\n'
    printf 'description = "%s"\n\n' \
      "$(printf '%s' "$2" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')"
    printf 'prompt = """\n%s\n"""\n' "$body"
  } > "$1"
}

build_staging(){
  local stage="$1" s f base desc hint
  for s in skills/*/; do
    s="${s%/}"; base="${s#skills/}"
    mkdir -p "$stage/agents-skills" "$stage/claude-skills"
    cp -R "$s" "$stage/agents-skills/$base"
    cp -R "$s" "$stage/claude-skills/$base"
    mkdir -p "$stage/codex-skills"
    rm -rf "$stage/codex-skills/$base"
    cp -R "$s" "$stage/codex-skills/$base"
  done
  for f in commands/*.md; do
    base="$(basename "$f" .md)"
    local d
    for d in claude-commands opencode-commands agents-commands cursor-commands windsurf-workflows codex-prompts; do
      mkdir -p "$stage/$d"; cp "$f" "$stage/$d/$base.md"
    done
    mkdir -p "$stage/copilot-prompts"; cp "$f" "$stage/copilot-prompts/$base.prompt.md"
    desc="$(fm_field description "$f")"
    hint="$(fm_field argument-hint "$f")"
    [ -n "$hint" ] && desc="$desc (args: $hint)"
    mkdir -p "$stage/gemini-commands"
    write_toml "$stage/gemini-commands/$base.toml" "$desc" "$(body_after_frontmatter "$f")"
  done
  for w in CLAUDE GEMINI; do
    printf '%s\n\n@AGENTS.md\n' "$WRAPPER_COMMENT" > "$stage/$w.md"
  done
}

TARGETS=(
  ".agents/skills:agents-skills"
  ".claude/skills:claude-skills"
  ".codex/skills:codex-skills"
  ".claude/commands:claude-commands"
  ".opencode/commands:opencode-commands"
  ".agents/commands:agents-commands"
  ".cursor/commands:cursor-commands"
  ".codex/prompts:codex-prompts"
  ".github/prompts:copilot-prompts"
  ".windsurf/workflows:windsurf-workflows"
  ".gemini/commands:gemini-commands"
)

deploy(){
  local stage="$1" p live staged
  for p in "${TARGETS[@]}"; do
    live="${p%%:*}"; staged="${p##*:}"
    rm -rf "$live"
    mkdir -p "$(dirname "$live")"
    cp -R "$stage/$staged" "$live"
    ok "$live/"
  done
  cp "$stage/CLAUDE.md" "$stage/GEMINI.md" .
  ok "CLAUDE.md + GEMINI.md (@AGENTS.md wrappers)"
  if [ -d .opencode/command ]; then  # legacy singular dir from the old layout
    git rm -rq --ignore-unmatch .opencode/command 2>/dev/null || rm -rf .opencode/command
    note "removed legacy .opencode/command/ (now .opencode/commands/)"
  fi
}

check(){
  local stage="$1" p live staged drift=0 w
  for p in "${TARGETS[@]}"; do
    live="${p%%:*}"; staged="${p##*:}"
    if diff -r "$live" "$stage/$staged" >/dev/null 2>&1; then
      ok "$live/"
    else
      miss "$live/" "drift — run scripts/sync-providers.sh"; drift=1
    fi
  done
  for w in CLAUDE.md GEMINI.md; do
    if cmp -s "$w" "$stage/$w"; then ok "$w"; else miss "$w" "drift — run scripts/sync-providers.sh"; drift=1; fi
  done
  if [ -d .opencode/command ]; then
    miss ".opencode/command/" "legacy dir — remove (now .opencode/commands/)"; drift=1
  fi
  return "$drift"
}

user_install(){
  local stage="$1" s base f
  for s in "$stage"/agents-skills/*/; do
    s="${s%/}"; base="${s##*/}"
    mkdir -p "$HOME/.agents/skills" "$HOME/.claude/skills" "$HOME/.codex/skills"
    rm -rf "$HOME/.agents/skills/$base" "$HOME/.claude/skills/$base" "$HOME/.codex/skills/$base"
    cp -R "$s" "$HOME/.agents/skills/$base"
    cp -R "$stage/claude-skills/$base" "$HOME/.claude/skills/$base"
    cp -R "$stage/codex-skills/$base" "$HOME/.codex/skills/$base"
    ok "skill $base" "~/.agents/skills + ~/.claude/skills + ~/.codex/skills"
  done
  mkdir -p "$HOME/.claude/commands" "$HOME/.agents/commands" \
           "$HOME/.config/opencode/commands" "$HOME/.gemini/commands" \
           "$HOME/.codex/prompts"
  for f in "$stage"/claude-commands/*.md; do
    cp "$f" "$HOME/.claude/commands/"
    cp "$f" "$HOME/.agents/commands/"
    cp "$f" "$HOME/.config/opencode/commands/"
  done
  for f in "$stage"/codex-prompts/*.md; do
    cp "$f" "$HOME/.codex/prompts/"
  done
  for f in "$stage"/gemini-commands/*.toml; do
    cp "$f" "$HOME/.gemini/commands/"
  done
  note "commands → ~/.claude/commands, ~/.agents/commands, ~/.config/opencode/commands (md), ~/.codex/prompts (md) + ~/.gemini/commands (toml)"
}

STAGE="$(mktemp -d "${TMPDIR:-/tmp}/mre-sync.XXXXXX")"
trap 'rm -rf "$STAGE"' EXIT
build_staging "$STAGE"

case "$MODE" in
  sync) deploy "$STAGE"; note "provider dirs regenerated from skills/ + commands/";;
  check) check "$STAGE" && note "no drift" || { note "drift detected"; exit 1; };;
  user)  user_install "$STAGE"; note "user-global install done";;
esac
